on:
  workflow_call:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
<<<<<<< before updating
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
=======
        uses: actions/checkout@v5
>>>>>>> after updating
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build sdist and wheel
        run: >
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) &&
          uvx --from build pyproject-build

      - name: Upload sdist and wheel as artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: dist
          path: dist

      - name: Check for packaging errors
        run: uvx twine check --strict dist/*

      - name: Install produced wheel
        run: python -m pip install dist/*.whl

      - name: Test module --version works using the installed wheel
        # If more than one module in src/ replace with module name to test
        run: python -m $(ls --hide='*.egg-info' src | head -1) --version
