on:
  workflow_call:
    inputs:
      tox:
        type: string
        description: What to run under tox
        required: true


jobs:
  run:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
<<<<<<< before updating
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
=======
        uses: actions/checkout@v5
>>>>>>> after updating

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run tox
        run: uv run --locked tox -e ${{ inputs.tox }}
